variables:
  APP_NAME: truckos
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1
  BUILDKIT_PROGRESS: plain #has docker builds output the results of their run command

workflow:
  name: 'Continuous Deployment'

include:
  - local: /gitlab/build-templates.yml
  - local: /gitlab/publish-templates.yml
  - local: /gitlab/deploy-templates.yml

stages:
  - build
  - publish
  - deploy

build-frontend-pr:
  extends: .build-frontend
  only:
    - external_pull_requests
  variables:
    ENV_FILE: .env.dev

build-backend-pr:
  extends: .build-backend
  only:
    - external_pull_requests
  variables:
    ENV_FILE: .env.dev

publish-frontend-dev:
  extends: .publish-frontend
  only:
    - main
  variables:
    ENV_FILE: .env.dev
  environment:
    name: dev
    url: https://dev.truckos.com
    action: prepare

publish-backend-dev:
  extends: .publish-backend
  only:
    - main
  variables:
    ENV_FILE: .env.dev
  environment:
    name: dev
    action: prepare
    url: https://dev.truckos.com


deploy-dev:
  extends: .deploy
  needs:
    - publish-frontend-dev
    - publish-backend-dev
  only:
    - main
  resource_group: dev
  variables:
    ENV_FILE: .env.dev
  environment:
    name: dev
    url: https://dev.truckos.com

publish-frontend-prod:
  extends: .publish-frontend
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    ENV_FILE: .env.prod
  environment:
    name: prod
    url: https://prod.truckos.com
    action: prepare

publish-backend-prod:
  extends: .publish-backend
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    ENV_FILE: .env.prod
  environment:
    name: prod
    action: prepare
    url: https://prod.truckos.com

deploy-prod:
  extends: .deploy
  needs:
    - publish-frontend-prod
    - publish-backend-prod
  rules:
    - if: $CI_COMMIT_TAG
  resource_group: prod
  variables:
    ENV_FILE: .env.prod
  environment:
    name: prod
    url: https://prod.truckos.com
