version: "3"
services:
  db:
    image:  postgres:13.1-alpine
    restart: always
    volumes:
    - ./create-dev-db.sh:/docker-entrypoint-initdb.d/create-dev-db.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: roqone_dev,roqone_test
      POSTGRES_USER: roqone
      POSTGRES_PASSWORD: roqone