export enum DebtorStatusEnum {
  CREATED = 'CREATED',
  IN_REVIEW = 'IN_REVIEW',
  VERIFIED = 'VERIFIED',
  UNKNOWN = 'UNKNOWN',
  DISABLED = 'DISABLED',
  EXPIRED = 'EXPIRED',
  REGISTERED = 'REGISTERED',
  DISABLED_BY_WALBING = 'DISABLED_BY_WALBING',
}
