const routeNames = Object.freeze({
  home: 'home',
  acceptInvite: 'accept-invite',
  accountActivate: 'account-activate',
  accountSettings: 'account-settings',
  accountActivateProviderLink: 'account-activate-provider-link',
  forgotPassword: 'forgot-password',
  login: 'login',
  messageCenter: 'message-center',
  profile: 'profile',
  register: 'register',
  restorePassword: 'restore-password',
  settings: 'settings',
  users: 'users',
  usersActive: 'users-active',
  usersInvited: 'users-invited',
  usersCanceled: 'users-canceled',
  usersInactive: 'users-inactive',
  userEdit: 'user-edit',
  files: 'files',
  filesEdit: 'files-edit',
  userProfile: 'user-profile',
  userInvitesEdit: 'user-invites-edit',
  imprint: 'imprint',
  terms: 'terms',
  privacy: 'privacy',
  dataPreferences: 'data-preferences',
  exampleAuthors: 'example-authors',
  exampleBooks: 'example-books',
  exampleCreateAuthor: 'example-create-author',
  exampleEditAuthor: 'example-edit-author',
  exampleCreateBook: 'example-create-book',
  exampleEditBook: 'example-edit-book',
  paymentDashboard: 'payment-dashboard',
  confirmTransaction: 'confirm-transaction',
  paymentStatus: 'payment-status',
  companyRegister: 'company-register',
  invoiceCreation: 'invoice-creation',
  invoiceDetails: 'invoice-details',
  accountPending: 'account-pending',
  userReceivables: 'users/receivables',
});

module.exports = routeNames;
