export const REPRESENTATIVE_OWNER_FIRST_NAME_FIELD = 0;
export const REPRESENTATIVE_OWNER_LAST_NAME_FIELD = 1;
export const REPRESENTATIVE__OWNER_EMAIL_FIELD = 2;
export const REPRESENTATIVE_OWNER_DATE_OF_BIRTH_FIELD = 3;
