import * as Joi from 'joi';

export const validationSchema = Joi.object({
  ROQ_ONE_API_KEY: Joi.string().default('CHANGE_ME_3'),
  API_URI: Joi.string().default('/graphql'),
  APP_ENVIRONMENT: Joi.string().default('development'),
  APP_PROJECT: Joi.string().default('roq-tech'),
  APP_NAME: Joi.string().default('roq-one-project'),
  BLACKLISTED_FIELDS: Joi.string().default('userEntity:password'), //Add fields with ',' to be split and for other entities add with space
  CLOUD_LOGS_ENABLED: Joi.bool().default(false),
  CLOUD_LOGS_NAME: Joi.string().default('roq-one-backend'),
  CONSOLE_LOGS_ENABLED: Joi.bool().default(true),
  DATABASE_LOGS: Joi.boolean().default(false),
  DB_COLLATION_LOCALES: Joi.string().default(''), // Use ';' to be split for other collations triplet [name:operators:collate]
  LOGS_SKIP_FIELDS: Joi.string().default('password'),
  DATABASE_URL: Joi.string().uri().default('postgres://roqone:roqone@localhost/roqone_dev'),
  DEBUG: Joi.boolean().default(false),
  DEFAULT_FILE_MAX_SIZE_BYTES: Joi.number().default(2000000), // default is 2MB
  DEFAULT_LANGUAGE: Joi.string().default('de_DE'),
  ENTITY_LISTENER_EVENTS_NAME: Joi.string().default('PROJECT'),
  FRONTEND_URL: Joi.string().default('http://localhost:3000'),
  INVITE_EMAIL_TYPE: Joi.string().default('USER_INVITE_MAIL'),
  JWT_SECRET: Joi.string().default('CHANGE_ME'),
  JWT_TTL: Joi.number().default(60 * 60), //1h
  LINK_TO_ACCOUNT_EXPIRES_HOURS: Joi.number().default(24),
  MAX_CONCURRENCY_LIMIT: Joi.number().default(3),
  MAX_INVITE_PER_REQUEST: Joi.number().default(10),
  NEW_RELIC_RECORD_SQL: Joi.string().default('raw'),
  NEW_RELIC_EXPLAIN_THRESHOLD: Joi.number().default(0),
  NEW_RELIC_TRACER_THRESHOLD: Joi.number().default(0),
  NEW_RELIC_SLOW_SQL_ENABLED: Joi.boolean().default(true),
  NEW_RELIC_ENABLE: Joi.boolean().default(false),
  NEW_RELIC_HOME: Joi.string().default('src/config'),
  PORT: Joi.number().port().default(3001),
  QUERY_LIMIT: Joi.number().default(1000),
  MAX_GRAPHQL_QUERY_DEPTH: Joi.number().default(4),
  QUERY_DEPTH_IGNORE_FIELDS: Joi.string().default('data'),
  RESET_PASSWORD_EXPIRES_HOURS: Joi.number().default(24),
  ROQ_PLATFORM_API_URI: Joi.string().default('/server/graphql'),
  ROQ_PLATFORM_AUTHORIZATION_HEADER: Joi.string().default('roq-platform-authorization'),
  ROQ_PLATFORM_REQUEST_ID_HEADER: Joi.string().default('request-id'),
  ROQ_PLATFORM_REQUEST_CALLER_HEADER: Joi.string().default('request-caller'),
  ROQ_PLATFORM_USER_ID_HEADER: Joi.string().default('roq-user-id'),
  ROQ_PLATFORM_URL: Joi.string().default('https://saturn-pp.roq-platform.com/v01'),
  API_KEY: Joi.string().default('92a606db-a767-458d-bc8b-05562ac514f8'),
  TENANT_ID: Joi.string().default('fbdaa685-d335-46f2-93a4-33ac4b4ef4ff'),
  ROQ_PLATFORM_USER_AUTHORIZATION_HEADER: Joi.string().default('roq-user-authorization'),
  ROQ_PLATFORM_USER_SYNC_CRON_INTERVAL: Joi.string().default('*/15 * * * * *'),
  VALIDATE_EMAIL_EXPIRES_HOURS: Joi.number().default(24),
  WRITE_SIGNED_URL_VALID_MS: Joi.number().default(86400000), //In milliesecond so default is 1 days
  AUTO_EMAIL_CONFIRMATION: Joi.boolean().default(false),
  IMPORT_DATA_CONFIG: Joi.string().default('demo'),
  ROQ_PLATFORM_SERVICE_ACCOUNT_EMAIL: Joi.string().default('project-service-account@roq.tech'),
  ROQ_PLATFORM_SERVICE_ACCOUNT_CACHE_TTL: Joi.number().default(60), // 1m
  ROQ_PLATFORM_SERVICE_ACCOUNT_TOKEN_CACHE_KEY: Joi.string().default('roq-platform-token'),
  IS_CONSOLE_COMMAND: Joi.boolean().default(false),
  WALBING_BASE_URL: Joi.string().default('https://ptest.walbing.com/jwt/v1.0'),
  WALBING_AUTHORIZATION_HEADER: Joi.string().default('Authorization'),
  WALBING_API_KEY: Joi.string().default(
    '2wmWUcrJ4HsgpVrC.MvWvcVXG6AkmglKQB9r/QM+KwS3ajzqN7SOc2pBD57O87C9LK2AiLGR3Rx8WRfVgHAjNsPaa1s+9LWCTYW1fJVumvbc7h2PR6mpUjTM4j3usCSWXDxfXiHdjCIn/+AiGLJ4kGdOZTbpbfp/rlRZZ5gzH5B9NZ8HrMF9rUFCK4Rk=',
  ),
  INVOICE_CURRENCY: Joi.string().default('EUR'),
  WALBING_INVITATION_CODE: Joi.string().default('WB-TRUCKOS'),
  BANK_TAG_NAME: Joi.string().default('Main Account'),
  API_KEY_HASH_SECRET: Joi.string().default('436b52e445218882608ef7a06fa82989'),
  WALBING_WEBHOOK_SECRET_KEY: Joi.string().default('1a1a9cafa49fa76e82ffee1543a884eeeeb9e8389f371a45f3e913524b7a3583'),
  SUPER_USERS: Joi.string().default('martin@truck-os.de,martin+4@truck-os.de'),
  SENDGRID_API_KEY: Joi.string().default('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'),
  BASE_URL: Joi.string().default('https://dev.truckos.com'),
  AWS_ACCESS_KEY_ID: Joi.string().default(''),
  AWS_SECRET_ACCESS_KEY: Joi.string().default(''),
  AWS_S3_SIGNED_URL_EXPIRE: Joi.string().default(900), //15 minutes
  AWS_S3_BUCKET_NAME: Joi.string().default('truck-os'),
});
